/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as BrandSetupRouteImport } from './routes/brand-setup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevPreviewGenerateRouteImport } from './routes/dev-preview.generate'
import { Route as DevPreviewBrandSetupRouteImport } from './routes/dev-preview.brand-setup'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandSetupRoute = BrandSetupRouteImport.update({
  id: '/brand-setup',
  path: '/brand-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPreviewGenerateRoute = DevPreviewGenerateRouteImport.update({
  id: '/dev-preview/generate',
  path: '/dev-preview/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const DevPreviewBrandSetupRoute = DevPreviewBrandSetupRouteImport.update({
  id: '/dev-preview/brand-setup',
  path: '/dev-preview/brand-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand-setup': typeof BrandSetupRoute
  '/generate': typeof GenerateRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev-preview/brand-setup': typeof DevPreviewBrandSetupRoute
  '/dev-preview/generate': typeof DevPreviewGenerateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand-setup': typeof BrandSetupRoute
  '/generate': typeof GenerateRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev-preview/brand-setup': typeof DevPreviewBrandSetupRoute
  '/dev-preview/generate': typeof DevPreviewGenerateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand-setup': typeof BrandSetupRoute
  '/generate': typeof GenerateRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev-preview/brand-setup': typeof DevPreviewBrandSetupRoute
  '/dev-preview/generate': typeof DevPreviewGenerateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand-setup'
    | '/generate'
    | '/privacy'
    | '/terms'
    | '/auth/callback'
    | '/dev-preview/brand-setup'
    | '/dev-preview/generate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand-setup'
    | '/generate'
    | '/privacy'
    | '/terms'
    | '/auth/callback'
    | '/dev-preview/brand-setup'
    | '/dev-preview/generate'
  id:
    | '__root__'
    | '/'
    | '/brand-setup'
    | '/generate'
    | '/privacy'
    | '/terms'
    | '/auth/callback'
    | '/dev-preview/brand-setup'
    | '/dev-preview/generate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandSetupRoute: typeof BrandSetupRoute
  GenerateRoute: typeof GenerateRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DevPreviewBrandSetupRoute: typeof DevPreviewBrandSetupRoute
  DevPreviewGenerateRoute: typeof DevPreviewGenerateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-setup': {
      id: '/brand-setup'
      path: '/brand-setup'
      fullPath: '/brand-setup'
      preLoaderRoute: typeof BrandSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-preview/generate': {
      id: '/dev-preview/generate'
      path: '/dev-preview/generate'
      fullPath: '/dev-preview/generate'
      preLoaderRoute: typeof DevPreviewGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-preview/brand-setup': {
      id: '/dev-preview/brand-setup'
      path: '/dev-preview/brand-setup'
      fullPath: '/dev-preview/brand-setup'
      preLoaderRoute: typeof DevPreviewBrandSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandSetupRoute: BrandSetupRoute,
  GenerateRoute: GenerateRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DevPreviewBrandSetupRoute: DevPreviewBrandSetupRoute,
  DevPreviewGenerateRoute: DevPreviewGenerateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
